import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/app/auth/(provider)/auth-provider";
import { Toaster } from "@/components/ui/sonner";

const libreFranklin = Libre_Franklin({
  variable: "--font-libre-franklin",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI-Cruiter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${libreFranklin.variable} antialiased`}>
        <AuthProvider>{children}</AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
